// USER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESSFUL = 'REGISTER_REQUEST_SUCCESSFUL';
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REQUEST_SUCCESSFUL = 'AUTH_REQUEST_SUCCESSFUL';
export const AUTH_REQUEST_FAILURE = 'AUTH_REQUEST_FAILURE';
export const DOCUMENT_TYPE_REQUEST = 'DOCUMENT_TYPE_REQUEST';
export const DOCUMENT_TYPE_REQUEST_SUCCESSFUL = 'DOCUMENT_TYPE_REQUEST_SUCCESSFUL';
export const DOCUMENT_TYPE_REQUEST_FAILURE = 'DOCUMENT_TYPE_REQUEST_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';

// VEHICLE_REQUEST
export const GET_VEHICLE_REQUEST = 'GET_VEHICLE_REQUEST'; 
export const GET_VEHICLE_REQUEST_SUCCESSFUL = 'GET_VEHICLE_REQUEST_SUCCESSFUL'; 
export const GET_VEHICLE_REQUEST_FAILURE = 'GET_VEHICLE_REQUEST_FAILURE'; 
export const CREATE_VEHICLE_REQUEST = 'CREATE_VEHICLE_REQUEST'; 
export const CREATE_VEHICLE_REQUEST_SUCCESSFUL = 'CREATE_VEHICLE_REQUEST_SUCCESFUL'; 
export const CREATE_VEHICLE_REQUEST_FAILURE = 'CREATE_VEHICLE_REQUEST_FAILURE'; 
export const DELETE_VEHICLE_REQUEST = 'DELETE_VEHICLE_REQUEST'; 
export const DELETE_VEHICLE_REQUEST_SUCCESSFUL = 'DELETE_VEHICLE_REQUEST_SUCCESSFUL'; 
export const DELETE_VEHICLE_REQUEST_FAILURE = 'DELETE_VEHICLE_REQUEST_FAILURE'; 
export const GET_VEHICLE_TYPES_REQUEST = 'GET_VEHICLE_TYPES_REQUEST'; 
export const GET_VEHICLE_TYPES_REQUEST_SUCCESSFUL = 'GET_VEHICLE_TYPES_REQUEST_SUCCESSFUL'; 
export const GET_VEHICLE_TYPES_REQUEST_FAILURE = 'GET_VEHICLE_TYPES_REQUEST_FAILURE'; 

// TRAVELS
export const GET_TRAVELS_REQUEST = 'GET_TRAVELS_REQUEST';
export const GET_TRAVELS_REQUEST_FAILURE = 'GET_TRAVELS_REQUEST_FAILURE';
export const GET_TRAVELS_REQUEST_SUCCESSFUL = 'GET_TRAVELS_REQUEST_SUCCESSFUL';
